name: Check Redirects

on:
  schedule:
    - cron: '0 19 * * *'  # 每天中国上海时间晚上3点运行一次
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run redirect checker
      run: |
        python check_redirects.py

    - name: Commit results
      run: |
        DATE=$(TZ='Asia/Shanghai' date +'%Y_%m_%d_%H_%M')
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          FILENAME="results/[Manual]check_results_$DATE.md"
        else
          FILENAME="results/[Actions]check_results_$DATE.md"
        fi
        mv check_results.md $FILENAME
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add $FILENAME
        git commit -m "Update check results for $DATE"
        git push
