name: Manage Results Folder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  manage-results-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove and recreate results folder
      run: |
        rm -rf results
        mkdir results
