name: Manage Results Folder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  manage-results-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove results folder
      run: |
        rm -rf results

    - name: Recreate results folder
      run: |
        mkdir results
        echo "This file was created on $(date)" > results/timestamp.txt

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add results
        git commit -m "Cleaned results folder"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
